# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build_and_Push
  displayName: Build and Push image
  jobs:
  - job: Build_And_Push
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: 'luispuc/lpsapigateway:$(tag)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
