[package]
name = "lps-api-gateway"
version = "0.1.0"
authors = ["luispsarmiento"]
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
serde = "1"
serde_derive = "1"
serde_json = "1"
reqwest = {version = "0.12.9", features = ["stream", "blocking", "json"]}
bytes = "1"
futures = "0.3"